### PR TITLE
Tendermint safety and fork scenarios

### PR DESCRIPTION
**Pull request by konnov**
Here is the specification of Tendermint safety that also includes fork scenarios. Although I am re-running the experiments with the updated spec, it would be great to have feedback on the spec.

### CODE REVIEW

**Comment by ebuchman** [comment]
Can we move this PR to the tendermint-rs repo? And anything else that needs to come along?

**Comment by ebuchman** [comment]
> Can we move this PR to the tendermint-rs repo? And anything else that needs to come along?

@konnov

**Comment by konnov** [comment]
Sure, I can do that. I guess, there is no other way but just introducing a new branch in tendermint-rs and introducing a PR? There is no special magic for that in github? :)

**Comment by konnov** [comment]
Moved to https://github.com/informalsystems/tendermint-rs/pull/496

**Pull request closed without merging**
